-- Tabla de canales configurados para notificaciones de Mapping Tracker por servidor
CREATE TABLE IF NOT EXISTS public.mapping_tracker_channels (
    guild_id TEXT PRIMARY KEY,
    channel_id TEXT NOT NULL,
    configured_by TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Tabla de suscripciones de mappers por servidor/canal y sus tipos de eventos
CREATE TABLE IF NOT EXISTS public.mapping_tracker_subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id TEXT NOT NULL,
    channel_id TEXT NOT NULL,
    osu_id BIGINT NOT NULL,
    event_types TEXT[] NOT NULL DEFAULT ARRAY['all'],
    added_by TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    CONSTRAINT unique_guild_osu_sub UNIQUE (guild_id, osu_id)
);

-- Index para búsquedas rápidas por osu_id y guild_id
CREATE INDEX IF NOT EXISTS idx_mapping_sub_osu_id ON public.mapping_tracker_subscriptions(osu_id);
CREATE INDEX IF NOT EXISTS idx_mapping_sub_guild_id ON public.mapping_tracker_subscriptions(guild_id);

-- Tabla de seguimiento de últimos eventos y snapshots de estado por mapper
CREATE TABLE IF NOT EXISTS public.mapping_tracker_last_events (
    osu_id BIGINT PRIMARY KEY,
    last_beatmapset_id BIGINT,
    last_updated_at TIMESTAMP WITH TIME ZONE,
    status_snapshot JSONB DEFAULT '{}'::jsonb,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);
